server:
  context-path: /demo/
  port: 9099

management:
  port: 9098
  address: 127.0.0.1

spring:
  datasource:
      test1db:
          name: test1db
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.1.19:3306/test1db?useUnicode=true&characterEncoding=UTF-8
          username: ENC(459BCC4C51BB1DA4) #test1db
          password: ENC(0883151783C641B7B8A4D55817A0337E) #test1dbPass
          driver-class-name: com.mysql.jdbc.Driver
          minIdle: 1
          maxActive: 2
          initialSize: 1
          timeBetweenEvictionRunsMillis: 3000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
      test2db:
          name: test2db
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.1.20:3306/test2db?useUnicode=true&characterEncoding=UTF-8
          username: ENC(2E5190DA1CE37E6A) #test2db
          password: ENC(7DB3746BEA9770B33CDEE7C3FDEEA661) #test2dbPass
          driver-class-name: com.mysql.jdbc.Driver
          minIdle: 1
          maxActive: 2
          initialSize: 1
          timeBetweenEvictionRunsMillis: 3000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false

#mybatis:
#  typeAliasesPackage: com.holmes.entity
#  mapperLocations: classpath:mapper/*.xml

