server:
  context-path: /demo/
  port: 9099

management:
  port: 9098
  address: 127.0.0.1

spring:
  datasource:
      test1db:
          name: test1db
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.1.19:3306/test1db?useUnicode=true&characterEncoding=UTF-8
          username: ENC(dGVzdDFkYg==) #test1db
          password: ENC(dGVzdDFkYlBhc3M=) #test1dbPass
          driver-class-name: com.mysql.jdbc.Driver
          minIdle: 1
          maxActive: 2
          initialSize: 1
          timeBetweenEvictionRunsMillis: 3000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
      test2db:
          name: test2db
          type: com.alibaba.druid.pool.DruidDataSource
          url: jdbc:mysql://192.168.1.20:3306/test2db?useUnicode=true&characterEncoding=UTF-8
          username: ENC(dGVzdDJkYg==) #test2db
          password: ENC(dGVzdDJkYlBhc3M=) #test2dbPass
          driver-class-name: com.mysql.jdbc.Driver
          minIdle: 1
          maxActive: 2
          initialSize: 1
          timeBetweenEvictionRunsMillis: 3000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false

#mybatis:
#  typeAliasesPackage: com.holmes.entity
#  mapperLocations: classpath:mapper/*.xml

